// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"CGMZ_Core","status":true,"description":"Core CGMZ Plugin, should be placed above all other CGMZ Plugins.","parameters":{"Check for Updates":"true","Dev Tools on Start":"false","Fullscreen":"false","Force Locale":"","Fallback Locale":"en-US","CGMZ Defaults":"","Scroll Speed":"1","Scroll Wait":"300","Scroll Deceleration":"0.92","Auto Scroll":"true","Add Space After Label":"true","CGMZ Controls":"","Scroll Up":"w","Scroll Down":"s","Playtest Options":"","Simulate Xbox Controller":"false","Simulate Playstation Controller":"false","Simulate Nintendo Controller":"false"}},
{"name":"CGMZ_NumPad","status":true,"description":"Number input processing that looks like a phone numpad","parameters":{"Scene Options":"","Window Width":"35","Sound Options":"","Number SE":"{\"Name\":\"\",\"Volume\":\"90\",\"Pitch\":\"100\",\"Pan\":\"0\"}","Volume Variance":"5","Pitch Variance":"5","Text Options":"","DEL Text":"DEL","OK Text":"OK","Integrations":"","Scene Background":"","Select Window Background":"","Current Window Background":"","Select Window Settings":"","Current Window Settings":""}},
{"name":"GALV_CharacterFramesMZ","status":true,"description":"Enables map character sheets to have more frames per character.","parameters":{"fSpeedMod":"f * 0.8","fileSymbol":"%"}},
{"name":"GALV_PuzzleFunctionsMZ","status":false,"description":"(v.1.1) A bunch of functions to use to make eventing puzzles easier\r\nView the plugin \"Help\" to view available commands.","parameters":{}},
{"name":"IceSlide","status":true,"description":"Ice Slide: Plays exactly 3 animation frames, then stays static.","parameters":{"IceTerrainTag":"2"}},
{"name":"SlidingPuzzle","status":true,"description":"4x4 Sliding Puzzle - High Priority Click Logic.","parameters":{"StartX":"24","StartY":"28","WinSwitch":"24"}},
{"name":"QuicksandSystem","status":true,"description":"Smooth 5px Quicksand: Visual cropping with Global Terrain Tags.","parameters":{"DefaultRegions":"[\"3\"]","DefaultTerrains":"[\"3\"]","DamageAmount":"50"}}
];
