// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"CGMZ_Core","status":true,"description":"Core CGMZ Plugin, should be placed above all other CGMZ Plugins.","parameters":{"Check for Updates":"true","Dev Tools on Start":"false","Fullscreen":"false","Force Locale":"","Fallback Locale":"en-US","CGMZ Defaults":"","Scroll Speed":"1","Scroll Wait":"300","Scroll Deceleration":"0.92","Auto Scroll":"true","Add Space After Label":"true","CGMZ Controls":"","Scroll Up":"w","Scroll Down":"s","Playtest Options":"","Simulate Xbox Controller":"false","Simulate Playstation Controller":"false","Simulate Nintendo Controller":"false"}},
{"name":"CGMZ_NumPad","status":true,"description":"Number input processing that looks like a phone numpad","parameters":{"Scene Options":"","Window Width":"35","Sound Options":"","Number SE":"{\"Name\":\"\",\"Volume\":\"90\",\"Pitch\":\"100\",\"Pan\":\"0\"}","Volume Variance":"5","Pitch Variance":"5","Text Options":"","DEL Text":"DEL","OK Text":"OK","Integrations":"","Scene Background":"","Select Window Background":"","Current Window Background":"","Select Window Settings":"","Current Window Settings":""}}
];
